dataset_dir: "/home/grads/tasnina/Projects/SynVerse/datasets/"

# Input Settings: initialize base input folder names,
# dataset collections, and models to run over
input_settings:
  # Base input directory
  input_dir: "/home/grads/tasnina/Projects/SynVerse/inputs/"

  drug_features:
    - name: 'd1hot'
      use: [ true, false]

    - name: 'target'
      preprocess: 'rwr'
      use: [true, false]

  cell_line_features:
    - name: 'c1hot'
      use: [true]

  models:
     decoder:
       name: 'MLP'
       hp_range: { 'lr': [ 1e-5, 1e-3 ], 'optimizer': [ 'Adam', 'SGD' ],
                   'sgd_momentum': [ 0.5, 0.99 ] ,
                   'num_hid_layers': [ 1,3 ] ,
                   'hid_0': [ 128, 256, 512, 1024, 2048, 4096 ],
                   'hid_1': [ 128, 256, 512, 1024, 2048, 4096 ],
                   'hid_2': [ 128, 256, 512, 1024, 2048, 4096 ],
                   'in_dropout_rate': [ 0.0, 0.5 ],
                   'hid_dropout_rate': [ 0.0, 0.5 ] }

       hp: {'hid_0': 1077, 'hid_dropout_rate': 0.2697798807963333, 'in_dropout_rate': 0.17927761184927016, 'lr': 0.00016381808734015385,
              'num_hid_layers': 2, 'optimizer': 'SGD', 'hid_1': 113, 'sgd_momentum': 0.21730082740135556}

  batch_size: 4096
  epochs: 10

  splits:
    - type: 'leave_comb'
      test_frac: 0.2
      val_frac: 0.25

    - type: 'leave_drug'
      test_frac: 0.2
      val_frac: 0.25

    - type: 'leave_cell_line'
      test_frac: 0.2
      val_frac: 0.25


  wandb:
    enabled: False
    token: 'd9462b91edea6523563900fab17134d7e9177e16'
    project_name: 'Synverse'
    entity_name: 'ntasnina'
    timezone: 'US/Eastern'
    timezone_format: '%Y-%m-%d_%H-%M-%S'
  bohb:
    min_budget: 27
    max_budget: 729
    n_iterations: 3
    run_id : 'synverse'
    server_type: 'local' #or cluster

  feature: 'must'
  abundance: 0.05

  max_feat: 1
  mode: 'debug'
        #'hp_tune' = hyperparam tuning and training the model with both train+val dataset
        # 'train' =  training the model with both train+val dataset
        # 'train_val' = train the model on training data and validate it on validation fold

output_settings:
  output_dir: '/home/grads/tasnina/Projects/SynVerse/outputs/'