dataset_dir: "/home/tasnina/Projects/SynVerse/datasets/"
# Input Settings: initialize base input folder names,
# dataset collections, and models to run over
input_settings:
  # Base input directory
  input_dir: "/home/tasnina/Projects/SynVerse/inputs/"

  drug_features:
    - name: '1hot'
      preprocess: null
      use: [true, false]
    - name: 'MACCS'
      preprocess: null
      use: [true, false]
#    - name: 'MFP'
#      preprocess: null
#    - name: 'ECFP_4'
#      preprocess: null

  cell_line_features:
    - name: '1hot'
      preprocess: null
      use: [true]
#    - name: 'genex'
#      preprocess: null

  models:
     - name: 'MLP'
       epochs: 10
       hp_range: { 'lr': [ 1e-5, 1e-2 ], 'optimizer': [ 'Adam', 'SGD' ] , 'sgd_momentum': [ 0.0, 0.99 ] ,
                   'num_hid_layers': [ 1,3 ] , 'hid_0': [ 64, 2048 ] , 'hid_1': [ 64,2048 ] , 'hid_2': [ 64, 2048 ] ,
                   'in_dropout_rate': [ 0.0, 0.5 ] ,'hid_dropout_rate': [ 0.0, 0.5 ] }
       hp: { 'lr': 0.00001, 'optimizer': 'Adam','num_hid_layers': 2 , 'hid_0': 1024, 'hid_1': 256,
             'in_dropout_rate': 0.2,'hid_dropout_rate': 0.5 }


  splits:
    - type: 'leave_drug'
      test_frac: 0.2
      n_folds: 5
    - type: 'leave_comb'
      test_frac: 0.2
      n_folds: 5
    - type: 'leave_cell_line'
      test_frac: 0.2
      n_folds: 5

  wandb: False
  bohb:
      min_budget: 27
      max_budget: 729
      n_iterations: 3
      run_id : 'example_1'
      server_type: 'local'

#      min_budget: 1
#      max_budget: 3
#      n_iterations: 1
#      run_id : 'example_1'
#      server_type: 'local' #or cluster

  feature: 'must'
  k: 6 #how many cell lines are being picked

output_settings:
  output_dir: '/home/tasnina/Projects/SynVerse/outputs/'