dataset_dir: "/home/tasnina/Projects/SynVerse/datasets/"

# Input Settings: initialize base input folder names,
# dataset collections, and models to run over
input_settings:
  # Base input directory
  input_dir: "/home/tasnina/Projects/SynVerse/inputs/"

  drug_features:

    - name: 'MACCS'
      use: [ false ]

    - name: 'ECFP_4'
      use: [false ]

    - name: 'MFP' #morgan fingerprint
      use: [false ]

    - name: 'mol_graph'
      encoder: 'GCN'
      use: [ false ]

    - name: 'smiles'
      encoder: 'SPMM'
      use: [ true ]

    - name: 'd1hot'
      use: [ false ]

  cell_line_features:
    - name: 'c1hot'
      use: [true]

  models:
     decoder:
       name: 'MLP'
       hp_range: { 'lr': [ 1e-5, 1e-3 ], 'optimizer': [ 'Adam', 'SGD' ],
                   'sgd_momentum': [ 0.5, 0.99 ] ,
                   'num_hid_layers': [ 1,3 ] ,
                   'hid_0': [ 128, 256, 512, 1024, 2048, 4096 ],
                   'hid_1': [ 128, 256, 512, 1024, 2048, 4096 ],
                   'hid_2': [ 128, 256, 512, 1024, 2048, 4096 ],
                   'in_dropout_rate': [ 0.0, 0.5 ],
                   'hid_dropout_rate': [ 0.0, 0.5 ] }

       hp: {'hid_0': 1077, 'hid_dropout_rate': 0.2697798807963333, 'in_dropout_rate': 0.17927761184927016, 'lr': 0.00016381808734015385,
              'num_hid_layers': 2, 'optimizer': 'SGD', 'hid_1': 113, 'sgd_momentum': 0.21730082740135556}

  batch_size: 4096
  epochs: 1500


  splits:
    - type: 'leave_comb'
      test_frac: 0.2
      val_frac: 0.25

    - type: 'leave_drug'
      test_frac: 0.2
      val_frac: 0.25

    - type: 'leave_cell_line'
      test_frac: 0.2
      val_frac: 0.25


  wandb:
    enabled: False
    token: 'd9462b91edea6523563900fab17134d7e9177e16'
    project_name: 'Synverse'
    entity_name: 'ntasnina'
    timezone: 'US/Eastern'
    timezone_format: '%Y-%m-%d_%H-%M-%S'
  bohb:
    min_budget: 27
    max_budget: 729
    n_iterations: 3
    server_type: 'local' #or cluster

  feature: 'must'
  abundance: 0.05

  max_feat: 1
  hp_tune: True
  train_mode:
    use_best_hyperparam: True # True: extract best hyperpam from results of hyperparam tune, False: use the param given in this config file.
output_settings:
  output_dir: '/home/tasnina/Projects/SynVerse/outputs/'